### ISSUE TITLE
`truncate_bytecode` not happy Solidity local imports

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/enigma-core#32]
**Describe the bug**
The new Enigma contract contains a local import: `import "./utils/SolRsaVerify.sol"`. This adds non-hex characters in the bytecode. Here is a snapshop of the `bytecode` field of `Enigma.json` for reference.
```
0000000000815290915073__SolRsaVerify__________________________90632ae0783d906126
```
This is compiled with Truffle 5. This causes a panic at line 90 here: https://github.com/enigmampc/enigma-core-internal/blob/develop/enigma-tools-u/src/web3_utils/w3utils.rs. 

@AvishaiW I'm only assigning this to you because I have to stop for the day. If you don't have time, I can take care of it.

**Comment by elichai** [comment]
This should fix this, please test it when you have time https://github.com/tomusdrw/rust-web3/pull/209

**Comment by AvishaiW** [comment]
@fredfortier what is the status on this issue? did you check if the PR elichai mentioned solves this issue?

**Comment by fredfortier** [comment]
I didn't re-test this but yes, I believe that `rust-web3` supports linked libraries now. Currently, interaction between the key mgmt node and the contract is tested externally in: https://github.com/enigmampc/enigma-contract/blob/master/enigma-js/test/Enigma.spec.js. This change would make possible to create equivalent more comprehensive unit tests.

**Comment by AvishaiW** [comment]
OK, so I'll close this issue for now and if it comes up we will reopen it. Thanks!
